In [1]:
from sklearn import preprocessing
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import shutil
import os
import requests
import base64


# Encode text values to dummy variables(i.e. [1,0,0],[0,1,0],[0,0,1] for red,green,blue)
# 더미 변수에 텍스트 값을 넣음.
def encode_text_dummy(df, name):
    dummies = pd.get_dummies(df[name])

    
    for x in dummies.columns:
        dummy_name = "{}-{}".format(name, x)
        df[dummy_name] = dummies[x]
    df.drop(name, axis=1, inplace=True)


# Encode text values to a single dummy variable.  The new columns (which do not replace the old) will have a 1
# at every location where the original column (name) matches each of the target_values.  One column is added for
# each target value.
# 텍스트 값을 단일 더미 변수로 인코딩. 새 열은 원래 열(이름)이 각 target_values와 일치하는 모든 위치에 1을 갖습니다. 하나의 열이 
# 각 목표값에 대해 추가됩니다.

def encode_text_single_dummy(df, name, target_values):
    for tv in target_values:
        l = list(df[name].astype(str))
        l = [1 if str(x) == str(tv) else 0 for x in l]
        name2 = "{}-{}".format(name, tv)
        df[name2] = l


# Encode text values to indexes(i.e. [1],[2],[3] for red,green,blue).
# 텍스트 벨류를 인덱스에 인코딩한다.
def encode_text_index(df, name):
    le = preprocessing.LabelEncoder()
    df[name] = le.fit_transform(df[name])
    return le.classes_


# Encode a numeric column as zscores
# 숫자 열을 z 점수로서 인코딩한다.
def encode_numeric_zscore(df, name, mean=None, sd=None):
    if mean is None:
        mean = df[name].mean()
        
    if sd is None:
        sd = df[name].std()
        
    df[name] = (df[name] - mean) / sd



# Convert all missing values in the specified column to the median
# 지정된 열의 누락된 값들을 평균값을 변경한다.
def missing_median(df, name):
    med = df[name].median()
    df[name] = df[name].fillna(med)


# Convert all missing values in the specified column to the default
# 지정된 열의 누락된 값들을 기본값으로 변경한다.
def missing_default(df, name, default_value):
    df[name] = df[name].fillna(default_value)


# Convert a Pandas dataframe to the x,y inputs that TensorFlow needs
# Pandas 데이터프레임을 x,y 입력값(TensorFlow가 필요한)으로 변환한다.
def to_xy(df, target):
    result = []

    for x in df.columns:
        if x != target:
            result.append(x)

    # find out the type of the target column.  Is it really this hard? :(
    # 목표 열의 타입을 찾아라.
    target_type = df[target].dtypes
#     print("Atarget_type:")
#     print(target_type)
    target_type = target_type[0]if hasattr(target_type, '__iter__') else target_type
#     print("Btarget_type:")
#     print(target_type)
    # Encode to int for classification, float otherwise. TensorFlow likes 32 bits.
    # 분류를 위해 int로 인코드하고 그렇지 않으면 float으로 한다. 32비트 TensorFlow와 같이.
#     print("np.int64:")
#     print(np.int64)
#     print("np.int32:")
#     print(np.int32)

    if target_type in (np.int64, np.int32):
        # Classification
        dummies = pd.get_dummies(df[target])
#         print("dummies")
#         print(dummies)
#         print("A")
        print("before")
        print(dummies.as_matrix())
        print("after")
        return df.as_matrix(result).astype(np.float32), dummies.as_matrix().astype(np.float32)
    else:
        # Regression
#         print("B")
        return df.as_matrix(result).astype(np.float32), df.as_matrix([target]).astype(np.float32)

# Nicely formatted time string
# 지정된 숫자 문자열
def hms_string(sec_elapsed):
    h = int(sec_elapsed / (60 * 60))
    m = int((sec_elapsed % (60 * 60)) / 60)
    s = sec_elapsed % 60
    return "{}:{:>02}:{:>05.2f}".format(h, m, s)


# Regression chart.
# Regression 차트
def chart_regression(pred,y,sort=True):
    t = pd.DataFrame({'pred' : pred, 'y' : y.flatten()})
    if sort:
        t.sort_values(by=['y'],inplace=True)
    a = plt.plot(t['y'].tolist(),label='expected')
    b = plt.plot(t['pred'].tolist(),label='prediction')
    plt.ylabel('output')
    plt.legend()
    plt.show()

# Remove all rows where the specified column is +/- sd standard deviations
# 지정된 열이 +/- 표준 편차인 모든 행 제거.
def remove_outliers(df, name, sd):
    drop_rows = df.index[(np.abs(df[name] - df[name].mean()) >= (sd * df[name].std()))]
    df.drop(drop_rows, axis=0, inplace=True)


# Encode a column to a range between normalized_low and normalized_high.
# normalized low와 normalized high 사이의 범위로 인코딩한다.
def encode_numeric_range(df, name, normalized_low=-1, normalized_high=1,
                         data_low=None, data_high=None):
    if data_low is None:
        data_low = min(df[name])
        data_high = max(df[name])

    df[name] = ((df[name] - data_low) / (data_high - data_low)) \
               * (normalized_high - normalized_low) + normalized_low
        
# This function submits an assignment.  You can submit an assignment as much as you like, only the final
# submission counts.  The paramaters are as follows:
# data - Pandas dataframe output.
# key - Your student key that was emailed to you.
# no - The assignment class number, should be 1 through 1.
# source_file - The full path to your Python or IPYNB file.  This must have "_class1" as part of its name.  
# .             The number must match your assignment number.  For example "_class2" for class assignment #2.

def submit(data,key,no,source_file=None):
    if source_file is None and '__file__' not in globals(): raise Exception('Must specify a filename when a Jupyter notebook.')
    if source_file is None: source_file = __file__
    suffix = '_class{}'.format(no)
    if suffix not in source_file: raise Exception('{} must be part of the filename.'.format(suffix))
    with open(source_file, "rb") as image_file:
        encoded_python = base64.b64encode(image_file.read()).decode('ascii')
    ext = os.path.splitext(source_file)[-1].lower()
    if ext not in ['.ipynb','.py']: raise Exception("Source file is {} must be .py or .ipynb".format(ext))
    r = requests.post("https://api.heatonresearch.com/assignment-submit",
        headers={'x-api-key':key}, json={'csv':base64.b64encode(data.to_csv(index=False).encode('ascii')).decode("ascii"),
        'assignment': no, 'ext':ext, 'py':encoded_python})
    if r.status_code == 200:
        print("Success: {}".format(r.text))
    else: print("Failure: {}".format(r.text))


In [2]:
from keras.utils.data_utils import get_file

try:
    path = get_file('kddcup.data_10_percent.gz', origin='http://kdd.ics.uci.edu/databases/kddcup99/kddcup.data_10_percent.gz')
    # 파일불러오기
except:
    print('Error downloading')
    raise
    
print(path)

# This file is a CSV, just no CSV extension or headers
# Download from: http://kdd.ics.uci.edu/databases/kddcup99/kddcup99.html
df = pd.read_csv(path, header=None)

print("Read {} rows.".format(len(df)))
# df = df.sample(frac=0.1, replace=False)
# Uncomment this line to sample only 10% of the dataset
# 데이터의 10%만 샘플링하려면 주석을 제거하세요.
df.dropna(inplace=True,axis=1) 
# For now, just drop NA's (rows with missing values)
# 지금, 행이 누락된 부분을 삭제하세요.
# The CSV file has no column heads, so add them
# CSV 파일에 열 머리글이 없으므로 추가하세요.
df.columns = [
    'duration',
    'protocol_type',
    'service',
    'flag',
    'src_bytes',
    'dst_bytes',
    'land',
    'wrong_fragment',
    'urgent',
    'hot',
    'num_failed_logins',
    'logged_in',
    'num_compromised',
    'root_shell',
    'su_attempted',
    'num_root',
    'num_file_creations',
    'num_shells',
    'num_access_files',
    'num_outbound_cmds',
    'is_host_login',
    'is_guest_login',
    'count',
    'srv_count',
    'serror_rate',
    'srv_serror_rate',
    'rerror_rate',
    'srv_rerror_rate',
    'same_srv_rate',
    'diff_srv_rate',
    'srv_diff_host_rate',
    'dst_host_count',
    'dst_host_srv_count',
    'dst_host_same_srv_rate',
    'dst_host_diff_srv_rate',
    'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate',
    'dst_host_serror_rate',
    'dst_host_srv_serror_rate',
    'dst_host_rerror_rate',
    'dst_host_srv_rerror_rate',
    'outcome'
]

# display 5 rows
df[0:10]


D:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


C:\Users\einju\.keras\datasets\kddcup.data_10_percent.gz
Read 494021 rows.


duration protocol_type service flag  src_bytes  dst_bytes  land  \
0         0           tcp    http   SF        181       5450     0   
1         0           tcp    http   SF        239        486     0   
2         0           tcp    http   SF        235       1337     0   
3         0           tcp    http   SF        219       1337     0   
4         0           tcp    http   SF        217       2032     0   
5         0           tcp    http   SF        217       2032     0   
6         0           tcp    http   SF        212       1940     0   
7         0           tcp    http   SF        159       4087     0   
8         0           tcp    http   SF        210        151     0   
9         0           tcp    http   SF        212        786     0   

   wrong_fragment  urgent  hot   ...     dst_host_srv_count  \
0               0       0    0   ...                      9   
1               0       0    0   ...                     19   
2               0       0    0   ...                     29   
3               0       0    0   ...                     39   
4               0       0    0   ...                     49   
5               0       0    0   ...                     59   
6               0       0    0   ...                     69   
7               0       0    0   ...                     79   
8               0       0    0   ...                     89   
9               0       0    1   ...                     99   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                     1.0                     0.0   
1                     1.0                     0.0   
2                     1.0                     0.0   
3                     1.0                     0.0   
4                     1.0                     0.0   
5                     1.0                     0.0   
6                     1.0                     0.0   
7                     1.0                     0.0   
8                     1.0                     0.0   
9                     1.0                     0.0   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.11                         0.00   
1                         0.05                         0.00   
2                         0.03                         0.00   
3                         0.03                         0.00   
4                         0.02                         0.00   
5                         0.02                         0.00   
6                         1.00                         0.04   
7                         0.09                         0.04   
8                         0.12                         0.04   
9                         0.12                         0.05   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                   0.0                       0.0                   0.0   
1                   0.0                       0.0                   0.0   
2                   0.0                       0.0                   0.0   
3                   0.0                       0.0                   0.0   
4                   0.0                       0.0                   0.0   
5                   0.0                       0.0                   0.0   
6                   0.0                       0.0                   0.0   
7                   0.0                       0.0                   0.0   
8                   0.0                       0.0                   0.0   
9                   0.0                       0.0                   0.0   

   dst_host_srv_rerror_rate  outcome  
0                       0.0  normal.  
1                       0.0  normal.  
2                       0.0  normal.  
3                       0.0  normal.  
4                       0.0  normal.  
5                       0.0  normal.  
6                       0.0  normal.  
7                       0.0  normal.  
8                       0.0  normal.  
9                       0.0  normal.  

[10 

In [3]:
# df.to_csv("result_10.csv", mode='w')

In [4]:
target_cnt=0;
target = "outcome";
for i in df.columns:
#     print(i);
    target_cnt=target_cnt+1;
    if(i == target):
        print(target_cnt);
        break;

target_cnt=target_cnt-1;

42


In [5]:
print(target_cnt)

41


In [6]:
target_df=df.iloc[:,target_cnt:target_cnt+1]

In [7]:
target_df.drop_duplicates()

outcome
0                normal.
744     buffer_overflow.
4049         loadmodule.
4113               perl.
7601            neptune.
7793              smurf.
15699      guess_passwd.
15784               pod.
19286          teardrop.
22814         portsweep.
26506           ipsweep.
31689              land.
39564         ftp_write.
39723              back.
40723              imap.
41727             satan.
42057               phf.
43067              nmap.
51965          multihop.
74079       warezmaster.
140030      warezclient.
140387              spy.
141509          rootkit.

In [8]:
df[target_cnt-1:target_cnt]

duration protocol_type service flag  src_bytes  dst_bytes  land  \
40         0           tcp    http   SF        370        520     0   

    wrong_fragment  urgent  hot   ...     dst_host_srv_count  \
40               0       0    0   ...                    255   

    dst_host_same_srv_rate  dst_host_diff_srv_rate  \
40                     1.0                     0.0   

    dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
40                         0.01                         0.04   

    dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
40                   0.0                       0.0                   0.0   

    dst_host_srv_rerror_rate  outcome  
40                       0.0  normal.  

[1 rows x 42 columns]

In [9]:
df.ix[0]

D:\anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


duration                             0
protocol_type                      tcp
service                           http
flag                                SF
src_bytes                          181
dst_bytes                         5450
land                                 0
wrong_fragment                       0
urgent                               0
hot                                  0
num_failed_logins                    0
logged_in                            1
num_compromised                      0
root_shell                           0
su_attempted                         0
num_root                             0
num_file_creations                   0
num_shells                           0
num_access_files                     0
num_outbound_cmds                    0
is_host_login                        0
is_guest_login                       0
count                                8
srv_count                            8
serror_rate                          0
srv_serror_rate          

In [10]:
# df[names.loc[:,'duration']]
df.shape

(494021, 42)

In [11]:
ENCODING = 'utf-8'

def expand_categories(values):
    result = []
    s = values.value_counts()
    # 특별한 값의 수를 포함한 객체
    t = float(len(values))
    for v in s.index:
        result.append("{}:{}%".format(v,round(100*(s[v]/t),2)))
    return "[{}]".format(",".join(result))
        
def analyze(filename):
    print()
    print("Analyzing: {}".format(filename))
    df = pd.read_csv(filename,encoding=ENCODING)
    cols = df.columns.values
    total = float(len(df))

    print("{} rows".format(int(total)))
    for col in cols:
        uniques = df[col].unique()
        # 해당 열의 특정 값을 리스트로 보여준다.
        unique_count = len(uniques)
        if unique_count>100:
            print("** {}:{} ({}%)".format(col,unique_count,int(((unique_count)/total)*100)))
        else:
            print("** {}:{}".format(col,expand_categories(df[col])))
            expand_categories(df[col])
            

In [12]:
# Analyze KDD-99

import tensorflow.contrib.learn as skflow
import pandas as pd
import os
import numpy as np
from sklearn import metrics
from scipy.stats import zscore

path = "./data/"

# 경로를 병합하여 새 경로 생성
filename_read = os.path.join(path,"auto-mpg.csv")
# ./data/auto-mpg.csv 로 경로 설정

In [13]:
# Now encode the feature vector
# feature 벡터로 인코딩한다.

# 숫자 열을 z 점수로서 인코딩한다. -> 숫자
encode_numeric_zscore(df, 'duration')
# 더미 변수에 텍스트 값을 넣음. -> 문자
encode_text_dummy(df, 'protocol_type')
encode_text_dummy(df, 'service')
encode_text_dummy(df, 'flag')
encode_numeric_zscore(df, 'src_bytes')
encode_numeric_zscore(df, 'dst_bytes')
encode_text_dummy(df, 'land')
encode_numeric_zscore(df, 'wrong_fragment')
encode_numeric_zscore(df, 'urgent')
encode_numeric_zscore(df, 'hot')
encode_numeric_zscore(df, 'num_failed_logins')
encode_text_dummy(df, 'logged_in')
encode_numeric_zscore(df, 'num_compromised')
encode_numeric_zscore(df, 'root_shell')
encode_numeric_zscore(df, 'su_attempted')
encode_numeric_zscore(df, 'num_root')
encode_numeric_zscore(df, 'num_file_creations')
encode_numeric_zscore(df, 'num_shells')
encode_numeric_zscore(df, 'num_access_files')
encode_numeric_zscore(df, 'num_outbound_cmds')
encode_text_dummy(df, 'is_host_login')
encode_text_dummy(df, 'is_guest_login')
encode_numeric_zscore(df, 'count')
encode_numeric_zscore(df, 'srv_count')
encode_numeric_zscore(df, 'serror_rate')
encode_numeric_zscore(df, 'srv_serror_rate')
encode_numeric_zscore(df, 'rerror_rate')
encode_numeric_zscore(df, 'srv_rerror_rate')
encode_numeric_zscore(df, 'same_srv_rate')
encode_numeric_zscore(df, 'diff_srv_rate')
encode_numeric_zscore(df, 'srv_diff_host_rate')
encode_numeric_zscore(df, 'dst_host_count')
encode_numeric_zscore(df, 'dst_host_srv_count')
encode_numeric_zscore(df, 'dst_host_same_srv_rate')
encode_numeric_zscore(df, 'dst_host_diff_srv_rate')
encode_numeric_zscore(df, 'dst_host_same_src_port_rate')
encode_numeric_zscore(df, 'dst_host_srv_diff_host_rate')
encode_numeric_zscore(df, 'dst_host_serror_rate')
encode_numeric_zscore(df, 'dst_host_srv_serror_rate')
encode_numeric_zscore(df, 'dst_host_rerror_rate')
encode_numeric_zscore(df, 'dst_host_srv_rerror_rate')
# 텍스트 value를 index에 인코딩한다.
outcomes = encode_text_index(df, 'outcome')
print("A")
print(outcomes)
num_classes = len(outcomes)

# display 5 rows

df.dropna(inplace=True,axis=1)
df[0:5]
# This is the numeric feature vector, as it goes to the neural net
# 숫자 feature 벡터, 신경망이다.

A
['back.' 'buffer_overflow.' 'ftp_write.' 'guess_passwd.' 'imap.'
 'ipsweep.' 'land.' 'loadmodule.' 'multihop.' 'neptune.' 'nmap.' 'normal.'
 'perl.' 'phf.' 'pod.' 'portsweep.' 'rootkit.' 'satan.' 'smurf.' 'spy.'
 'teardrop.' 'warezclient.' 'warezmaster.']


duration  src_bytes  dst_bytes  wrong_fragment    urgent       hot  \
0 -0.067792  -0.002879   0.138664        -0.04772 -0.002571 -0.044136   
1 -0.067792  -0.002820  -0.011578        -0.04772 -0.002571 -0.044136   
2 -0.067792  -0.002824   0.014179        -0.04772 -0.002571 -0.044136   
3 -0.067792  -0.002840   0.014179        -0.04772 -0.002571 -0.044136   
4 -0.067792  -0.002842   0.035214        -0.04772 -0.002571 -0.044136   

   num_failed_logins  num_compromised  root_shell  su_attempted  \
0          -0.009782        -0.005679   -0.010552     -0.004676   
1          -0.009782        -0.005679   -0.010552     -0.004676   
2          -0.009782        -0.005679   -0.010552     -0.004676   
3          -0.009782        -0.005679   -0.010552     -0.004676   
4          -0.009782        -0.005679   -0.010552     -0.004676   

         ...         flag-S3  flag-SF  flag-SH  land-0  land-1  logged_in-0  \
0        ...               0        1        0       1       0            0   
1        ...               0        1        0       1       0            0   
2        ...               0        1        0       1       0            0   
3        ...               0        1        0       1       0            0   
4        ...               0        1        0       1       0            0   

   logged_in-1  is_host_login-0  is_guest_login-0  is_guest_login-1  
0            1                1                 1                 0  
1            1                1                 1                 0  
2            1                1                 1                 0  
3            1                1                 1                 0  
4            1                1                 1                 0  

[5 rows x 121 columns]

In [56]:
import pandas as pd
import io
import requests
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn import metrics
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.callbacks import EarlyStopping


# Break into X (predictors) & y (prediction)
# X( 예측 변수) & y( 예측값)으로 나누기
x, y = to_xy(df,'outcome')

# print("A")
# print(x)
# print(x.shape)

# print("B")
# print(y)
# print(y.shape)

# Create a test/train split.  25% test
# Split into train/test
# test와 train을 나눈다. 
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.25, random_state=42)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

before
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
after
(370515, 120)
(370515, 23)
(123506, 120)
(123506, 23)


In [57]:
# model = sequential()
# model.add()

# Create neural net
# neural net을 만든다.
# 레이어 구성
# conv 구조와 relu 
import time

start_vect=time.time()

model = Sequential()
model.add(Dense(10, input_dim=x.shape[1], kernel_initializer='normal', activation='relu'))
model.add(Dense(50, input_dim=x.shape[1], kernel_initializer='normal', activation='relu'))
model.add(Dense(10, input_dim=x.shape[1], kernel_initializer='normal', activation='relu'))
model.add(Dense(1, kernel_initializer='normal'))
model.add(Dense(y.shape[1], activation='softmax'))
# 학습 프로세스 설정
model.compile(loss='categorical_crossentropy', optimizer='adam')
# 학습 데이터로 학습.
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=5, verbose=1, mode='auto')
model.fit(x_train,y_train,validation_data=(x_test,y_test),callbacks=[monitor],verbose=2,epochs=1)

Train on 370515 samples, validate on 123506 samples
Epoch 1/1
 - 31s - loss: 0.1839 - val_loss: 0.0751


In [58]:
print (x_train[1:10])
print (y_train[1:10])

[[ 0.02263621 -0.00184232  0.07601294 ...  1.          0.
   1.        ]
 [-0.06779165 -0.00306168 -0.0262873  ...  1.          1.
   0.        ]
 [-0.06779165 -0.00306168 -0.0262873  ...  1.          1.
   0.        ]
 ...
 [-0.06779165 -0.00284614  0.7460795  ...  1.          1.
   0.        ]
 [-0.06779165 -0.00201738 -0.0262873  ...  1.          1.
   0.        ]
 [-0.06779165 -0.00276317  0.04774417 ...  1.          1.
   0.        ]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [59]:
print (x_train.shape)
print (x_test.shape)
print (len(y_train[0]))

(370515, 120)
(123506, 120)
23


In [60]:
print (x_train[0])

[-0.06779165 -0.00253548 -0.0262873  -0.04772014 -0.00257147 -0.04413587
 -0.00978217 -0.00567868 -0.01055194 -0.00467567 -0.00564001 -0.01123207
 -0.00991896 -0.02763179  0.83845407  0.88539684 -0.46408927 -0.46352
 -0.24796022 -0.24863103  0.5369869  -0.25524312 -0.20363286  0.3479665
  0.62555695  0.5993956  -0.2828664   0.82704675 -0.15862913 -0.46441716
 -0.4632019  -0.25203925 -0.24946375  1.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          1.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.  

In [61]:
cnt = 0
for y in y_test:
    if y[0] == 1:
        cnt+=1
        
print (cnt)

541


In [62]:
# Measure accuracy
pred = model.predict(x_test)
pred = np.argmax(pred,axis=1)
y_eval = np.argmax(y_test,axis=1)
score = metrics.accuracy_score(y_eval, pred)
print("Validation score: {}".format(score))
print("training Runtime: %0.2f Minutes"%((time.time() - start_vect)/60))

Validation score: 0.9832801645264198
training Runtime: 0.59 Minutes


In [63]:
model.save('keras.h5')

In [47]:
# 데이터 처리 / 결과 나눠서 보여주기 / feature selection / 성능 비교 / 시간