In [2]:
from sklearn import preprocessing
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import shutil
import os
import requests
import base64


# Encode text values to dummy variables(i.e. [1,0,0],[0,1,0],[0,0,1] for red,green,blue)
# 더미 변수에 텍스트 값을 넣음.
def encode_text_dummy(df, name):
    dummies = pd.get_dummies(df[name])

    
    for x in dummies.columns:
        dummy_name = "{}-{}".format(name, x)
        df[dummy_name] = dummies[x]
    df.drop(name, axis=1, inplace=True)


# Encode text values to a single dummy variable.  The new columns (which do not replace the old) will have a 1
# at every location where the original column (name) matches each of the target_values.  One column is added for
# each target value.
# 텍스트 값을 단일 더미 변수로 인코딩. 새 열은 원래 열(이름)이 각 target_values와 일치하는 모든 위치에 1을 갖습니다. 하나의 열이 
# 각 목표값에 대해 추가됩니다.

def encode_text_single_dummy(df, name, target_values):
    for tv in target_values:
        l = list(df[name].astype(str))
        l = [1 if str(x) == str(tv) else 0 for x in l]
        name2 = "{}-{}".format(name, tv)
        df[name2] = l


# Encode text values to indexes(i.e. [1],[2],[3] for red,green,blue).
# 텍스트 벨류를 인덱스에 인코딩한다.
def encode_text_index(df, name):
    le = preprocessing.LabelEncoder()
    df[name] = le.fit_transform(df[name])
    return le.classes_


# Encode a numeric column as zscores
# 숫자 열을 z 점수로서 인코딩한다.
def encode_numeric_zscore(df, name, mean=None, sd=None):
    if mean is None:
        mean = df[name].mean()
        
    if sd is None:
        sd = df[name].std()
        
    df[name] = (df[name] - mean) / sd



# Convert all missing values in the specified column to the median
# 지정된 열의 누락된 값들을 평균값을 변경한다.
def missing_median(df, name):
    med = df[name].median()
    df[name] = df[name].fillna(med)


# Convert all missing values in the specified column to the default
# 지정된 열의 누락된 값들을 기본값으로 변경한다.
def missing_default(df, name, default_value):
    df[name] = df[name].fillna(default_value)


# Convert a Pandas dataframe to the x,y inputs that TensorFlow needs
# Pandas 데이터프레임을 x,y 입력값(TensorFlow가 필요한)으로 변환한다.
def to_xy(df, target):
    result = []

    for x in df.columns:
        if x != target:
            result.append(x)

    # find out the type of the target column.  Is it really this hard? :(
    # 목표 열의 타입을 찾아라.
    target_type = df[target].dtypes
#     print("Atarget_type:")
#     print(target_type)
    target_type = target_type[0]if hasattr(target_type, '__iter__') else target_type
#     print("Btarget_type:")
#     print(target_type)
    # Encode to int for classification, float otherwise. TensorFlow likes 32 bits.
    # 분류를 위해 int로 인코드하고 그렇지 않으면 float으로 한다. 32비트 TensorFlow와 같이.
#     print("np.int64:")
#     print(np.int64)
#     print("np.int32:")
#     print(np.int32)

    if target_type in (np.int64, np.int32):
        # Classification
        dummies = pd.get_dummies(df[target])
#         print("dummies")
#         print(dummies)
#         print("A")
        print("before")
        print(dummies.as_matrix())
        print("after")
        return df.as_matrix(result).astype(np.float32), dummies.as_matrix().astype(np.float32)
    else:
        # Regression
#         print("B")
        return df.as_matrix(result).astype(np.float32), df.as_matrix([target]).astype(np.float32)

# Nicely formatted time string
# 지정된 숫자 문자열
def hms_string(sec_elapsed):
    h = int(sec_elapsed / (60 * 60))
    m = int((sec_elapsed % (60 * 60)) / 60)
    s = sec_elapsed % 60
    return "{}:{:>02}:{:>05.2f}".format(h, m, s)


# Regression chart.
# Regression 차트
def chart_regression(pred,y,sort=True):
    t = pd.DataFrame({'pred' : pred, 'y' : y.flatten()})
    if sort:
        t.sort_values(by=['y'],inplace=True)
    a = plt.plot(t['y'].tolist(),label='expected')
    b = plt.plot(t['pred'].tolist(),label='prediction')
    plt.ylabel('output')
    plt.legend()
    plt.show()

# Remove all rows where the specified column is +/- sd standard deviations
# 지정된 열이 +/- 표준 편차인 모든 행 제거.
def remove_outliers(df, name, sd):
    drop_rows = df.index[(np.abs(df[name] - df[name].mean()) >= (sd * df[name].std()))]
    df.drop(drop_rows, axis=0, inplace=True)


# Encode a column to a range between normalized_low and normalized_high.
# normalized low와 normalized high 사이의 범위로 인코딩한다.
def encode_numeric_range(df, name, normalized_low=-1, normalized_high=1,
                         data_low=None, data_high=None):
    if data_low is None:
        data_low = min(df[name])
        data_high = max(df[name])

    df[name] = ((df[name] - data_low) / (data_high - data_low)) \
               * (normalized_high - normalized_low) + normalized_low
        
# This function submits an assignment.  You can submit an assignment as much as you like, only the final
# submission counts.  The paramaters are as follows:
# data - Pandas dataframe output.
# key - Your student key that was emailed to you.
# no - The assignment class number, should be 1 through 1.
# source_file - The full path to your Python or IPYNB file.  This must have "_class1" as part of its name.  
# .             The number must match your assignment number.  For example "_class2" for class assignment #2.

def submit(data,key,no,source_file=None):
    if source_file is None and '__file__' not in globals(): raise Exception('Must specify a filename when a Jupyter notebook.')
    if source_file is None: source_file = __file__
    suffix = '_class{}'.format(no)
    if suffix not in source_file: raise Exception('{} must be part of the filename.'.format(suffix))
    with open(source_file, "rb") as image_file:
        encoded_python = base64.b64encode(image_file.read()).decode('ascii')
    ext = os.path.splitext(source_file)[-1].lower()
    if ext not in ['.ipynb','.py']: raise Exception("Source file is {} must be .py or .ipynb".format(ext))
    r = requests.post("https://api.heatonresearch.com/assignment-submit",
        headers={'x-api-key':key}, json={'csv':base64.b64encode(data.to_csv(index=False).encode('ascii')).decode("ascii"),
        'assignment': no, 'ext':ext, 'py':encoded_python})
    if r.status_code == 200:
        print("Success: {}".format(r.text))
    else: print("Failure: {}".format(r.text))


In [3]:
import csv 

# df = open('KDDTrain+.csv','r',encoding='utf-8')
df = pd.read_csv('KDDTrain+.csv', header=None)
# 열 43
print("Read {} rows.".format(len(df)))

Read 125973 rows.


In [4]:
df.dropna(inplace=True, axis=1)

In [5]:
df.columns = [
    'duration',
    'protocol_type',
    'service',
    'flag',
    'src_bytes',
    'dst_bytes',
    'land',
    'wrong_fragment',
    'urgent',
    'hot',
    'num_failed_logins',
    'logged_in',
    'num_compromised',
    'root_shell',
    'su_attempted',
    'num_root',
    'num_file_creations',
    'num_shells',
    'num_access_files',
    'num_outbound_cmds',
    'is_host_login',
    'is_guest_login',
    'count',
    'srv_count',
    'serror_rate',
    'srv_serror_rate',
    'rerror_rate',
    'srv_rerror_rate',
    'same_srv_rate',
    'diff_srv_rate',
    'srv_diff_host_rate',
    'dst_host_count',
    'dst_host_srv_count',
    'dst_host_same_srv_rate',
    'dst_host_diff_srv_rate',
    'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate',
    'dst_host_serror_rate',
    'dst_host_srv_serror_rate',
    'dst_host_rerror_rate',
    'dst_host_srv_rerror_rate',
    'outcome',
    'question'
]

In [6]:
del df['question']

In [7]:
df[0:5]

duration protocol_type   service flag  src_bytes  dst_bytes  land  \
0         0           tcp  ftp_data   SF        491          0     0   
1         0           udp     other   SF        146          0     0   
2         0           tcp   private   S0          0          0     0   
3         0           tcp      http   SF        232       8153     0   
4         0           tcp      http   SF        199        420     0   

   wrong_fragment  urgent  hot   ...     dst_host_srv_count  \
0               0       0    0   ...                     25   
1               0       0    0   ...                      1   
2               0       0    0   ...                     26   
3               0       0    0   ...                    255   
4               0       0    0   ...                    255   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                    0.17                    0.03   
1                    0.00                    0.60   
2                    0.10                    0.05   
3                    1.00                    0.00   
4                    1.00                    0.00   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.17                         0.00   
1                         0.88                         0.00   
2                         0.00                         0.00   
3                         0.03                         0.04   
4                         0.00                         0.00   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                  0.00                      0.00                  0.05   
1                  0.00                      0.00                  0.00   
2                  1.00                      1.00                  0.00   
3                  0.03                      0.01                  0.00   
4                  0.00                      0.00                  0.00   

   dst_host_srv_rerror_rate  outcome  
0                      0.00   normal  
1                      0.00   normal  
2                      0.00  neptune  
3                      0.01   normal  
4                      0.00   normal  

[5 rows x 42 columns]

In [11]:
df = pd.DataFrame(df)

In [12]:
df

duration protocol_type     service flag  src_bytes  dst_bytes  land  \
0              0           tcp    ftp_data   SF        491          0     0   
1              0           udp       other   SF        146          0     0   
2              0           tcp     private   S0          0          0     0   
3              0           tcp        http   SF        232       8153     0   
4              0           tcp        http   SF        199        420     0   
5              0           tcp     private  REJ          0          0     0   
6              0           tcp     private   S0          0          0     0   
7              0           tcp     private   S0          0          0     0   
8              0           tcp  remote_job   S0          0          0     0   
9              0           tcp     private   S0          0          0     0   
10             0           tcp     private  REJ          0          0     0   
11             0           tcp     private   S0          0          0     0   
12             0           tcp        http   SF        287       2251     0   
13             0           tcp    ftp_data   SF        334          0     0   
14             0           tcp        name   S0          0          0     0   
15             0           tcp  netbios_ns   S0          0          0     0   
16             0           tcp        http   SF        300      13788     0   
17             0          icmp       eco_i   SF         18          0     0   
18             0           tcp        http   SF        233        616     0   
19             0           tcp        http   SF        343       1178     0   
20             0           tcp         mtp   S0          0          0     0   
21             0           tcp     private   S0          0          0     0   
22             0           tcp        http   SF        253      11905     0   
23          5607           udp       other   SF        147        105     0   
24             0           tcp         mtp   S0          0          0     0   
25           507           tcp      telnet   SF        437      14421     0   
26             0           tcp     private   S0          0          0     0   
27             0           tcp        http   SF        227       6588     0   
28             0           tcp        http   SF        215      10499     0   
29             0           tcp        http   SF        241       1400     0   
...          ...           ...         ...  ...        ...        ...   ...   
125943         0           tcp    ftp_data   SF        491          0     0   
125944         1           tcp        smtp   SF       2049        362     0   
125945         0           tcp        http   SF        247        799     0   
125946         0           tcp      finger   S0          0          0     0   
125947         0          icmp       eco_i   SF         18          0     0   
125948         0           tcp     private   S0          0          0     0   
125949         0           tcp        http  REJ          0          0     0   
125950         0           udp     private   SF         28          0     0   
125951         0           tcp        http   SF        254        555     0   
125952         0           tcp        smtp   SF       1289        408     0   
125953         0           tcp        auth   S0          0          0     0   
125954         0           tcp        http   SF        269      10939     0   
125955         0           tcp        http  REJ          0          0     0   
125956         0          icmp       eco_i   SF         30          0     0   
125957         1           tcp        smtp   SF       1247        327     0   
125958         0           tcp     private   S0          0          0     0   
125959         0           tcp        http   SF        373       4777     0   
125960         0           tcp        http   SF        329        885     0   
125961         0           tcp        http   SF        236

In [52]:
ENCODING = 'utf-8'

def expand_categories(values):
    result = []
    s = values.value_counts()
    # 특별한 값의 수를 포함한 객체
    t = float(len(values))
    for v in s.index:
        result.append("{}:{}%".format(v,round(100*(s[v]/t),2)))
    return "[{}]".format(",".join(result))
        
def analyze(filename):
    print()
    print("Analyzing: {}".format(filename))
    df = pd.read_csv(filename,encoding=ENCODING)
    cols = df.columns.values
    total = float(len(df))

    print("{} rows".format(int(total)))
    for col in cols:
        uniques = df[col].unique()
        # 해당 열의 특정 값을 리스트로 보여준다.
        unique_count = len(uniques)
        if unique_count>100:
            print("** {}:{} ({}%)".format(col,unique_count,int(((unique_count)/total)*100)))
        else:
            print("** {}:{}".format(col,expand_categories(df[col])))
            expand_categories(df[col])
            

In [53]:
# Analyze KDD-99

import tensorflow.contrib.learn as skflow
import pandas as pd
import os
import numpy as np
from sklearn import metrics
from scipy.stats import zscore

path = "./data/"

# 경로를 병합하여 새 경로 생성
filename_read = os.path.join(path,"auto-mpg.csv")
# ./data/auto-mpg.csv 로 경로 설정

In [54]:
# Now encode the feature vector
# feature 벡터로 인코딩한다.

# 숫자 열을 z 점수로서 인코딩한다. -> 숫자
encode_numeric_zscore(df, 'duration')
# 더미 변수에 텍스트 값을 넣음. -> 문자
encode_text_dummy(df, 'protocol_type')
encode_text_dummy(df, 'service')
encode_text_dummy(df, 'flag')
encode_numeric_zscore(df, 'src_bytes')
encode_numeric_zscore(df, 'dst_bytes')
encode_text_dummy(df, 'land')
encode_numeric_zscore(df, 'wrong_fragment')
encode_numeric_zscore(df, 'urgent')
encode_numeric_zscore(df, 'hot')
encode_numeric_zscore(df, 'num_failed_logins')
encode_text_dummy(df, 'logged_in')
encode_numeric_zscore(df, 'num_compromised')
encode_numeric_zscore(df, 'root_shell')
encode_numeric_zscore(df, 'su_attempted')
encode_numeric_zscore(df, 'num_root')
encode_numeric_zscore(df, 'num_file_creations')
encode_numeric_zscore(df, 'num_shells')
encode_numeric_zscore(df, 'num_access_files')
encode_numeric_zscore(df, 'num_outbound_cmds')
encode_text_dummy(df, 'is_host_login')
encode_text_dummy(df, 'is_guest_login')
encode_numeric_zscore(df, 'count')
encode_numeric_zscore(df, 'srv_count')
encode_numeric_zscore(df, 'serror_rate')
encode_numeric_zscore(df, 'srv_serror_rate')
encode_numeric_zscore(df, 'rerror_rate')
encode_numeric_zscore(df, 'srv_rerror_rate')
encode_numeric_zscore(df, 'same_srv_rate')
encode_numeric_zscore(df, 'diff_srv_rate')
encode_numeric_zscore(df, 'srv_diff_host_rate')
encode_numeric_zscore(df, 'dst_host_count')
encode_numeric_zscore(df, 'dst_host_srv_count')
encode_numeric_zscore(df, 'dst_host_same_srv_rate')
encode_numeric_zscore(df, 'dst_host_diff_srv_rate')
encode_numeric_zscore(df, 'dst_host_same_src_port_rate')
encode_numeric_zscore(df, 'dst_host_srv_diff_host_rate')
encode_numeric_zscore(df, 'dst_host_serror_rate')
encode_numeric_zscore(df, 'dst_host_srv_serror_rate')
encode_numeric_zscore(df, 'dst_host_rerror_rate')
encode_numeric_zscore(df, 'dst_host_srv_rerror_rate')
# 텍스트 value를 index에 인코딩한다.
outcomes = encode_text_index(df, 'outcome')
# print("A")
# print(outcomes)
num_classes = len(outcomes)

# display 5 rows

df.dropna(inplace=True,axis=1)
df[0:5]
# This is the numeric feature vector, as it goes to the neural net
# 숫자 feature 벡터, 신경망이다.

duration  src_bytes  dst_bytes  wrong_fragment    urgent       hot  \
0 -0.110249  -0.007679  -0.004919       -0.089486 -0.007736 -0.095075   
1 -0.110249  -0.007737  -0.004919       -0.089486 -0.007736 -0.095075   
2 -0.110249  -0.007762  -0.004919       -0.089486 -0.007736 -0.095075   
3 -0.110249  -0.007723  -0.002891       -0.089486 -0.007736 -0.095075   
4 -0.110249  -0.007728  -0.004814       -0.089486 -0.007736 -0.095075   

   num_failed_logins  num_compromised  root_shell  su_attempted  \
0          -0.027023        -0.011664   -0.036652     -0.024436   
1          -0.027023        -0.011664   -0.036652     -0.024436   
2          -0.027023        -0.011664   -0.036652     -0.024436   
3          -0.027023        -0.011664   -0.036652     -0.024436   
4          -0.027023        -0.011664   -0.036652     -0.024436   

         ...         flag-SF  flag-SH  land-0  land-1  logged_in-0  \
0        ...               1        0       1       0            1   
1        ...               1        0       1       0            1   
2        ...               0        0       1       0            1   
3        ...               1        0       1       0            0   
4        ...               1        0       1       0            0   

   logged_in-1  is_host_login-0  is_host_login-1  is_guest_login-0  \
0            0                1                0                 1   
1            0                1                0                 1   
2            0                1                0                 1   
3            1                1                0                 1   
4            1                1                0                 1   

   is_guest_login-1  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  

[5 rows x 126 columns]

In [55]:
total_rows = df['duration'].count
print(total_rows)

<bound method Series.count of 0        -0.110249
1        -0.110249
2        -0.110249
3        -0.110249
4        -0.110249
5        -0.110249
6        -0.110249
7        -0.110249
8        -0.110249
9        -0.110249
10       -0.110249
11       -0.110249
12       -0.110249
13       -0.110249
14       -0.110249
15       -0.110249
16       -0.110249
17       -0.110249
18       -0.110249
19       -0.110249
20       -0.110249
21       -0.110249
22       -0.110249
23        2.042551
24       -0.110249
25        0.084413
26       -0.110249
27       -0.110249
28       -0.110249
29       -0.110249
            ...   
125943   -0.110249
125944   -0.109865
125945   -0.110249
125946   -0.110249
125947   -0.110249
125948   -0.110249
125949   -0.110249
125950   -0.110249
125951   -0.110249
125952   -0.110249
125953   -0.110249
125954   -0.110249
125955   -0.110249
125956   -0.110249
125957   -0.109865
125958   -0.110249
125959   -0.110249
125960   -0.110249
125961   -0.110249
125962   -0.110249
1

In [56]:
import pandas as pd
import io
import requests
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn import metrics
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.callbacks import EarlyStopping

# Break into X (predictors) & y (prediction)
# X( 예측 변수) & y( 예측값)으로 나누기
x, y = to_xy(df,'outcome')

# print("A")
# print(x)
# print(x.shape)

# print("B")
# print(y)
# print(y.shape)

# Create a test/train split.  25% test
# Split into train/test
# test와 train을 나눈다. 
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.25, random_state=42)

print(y_test)


before
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
after
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [57]:
from sklearn.ensemble import RandomForestClassifier
import time

start_vect=time.time()
rf = RandomForestClassifier(n_estimators=100, oob_score=True, random_state=123456)
rf.fit(x_train, y_train)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=True, random_state=123456, verbose=0,
            warm_start=False)

In [58]:
from sklearn.metrics import accuracy_score

predicted = rf.predict(x_test)
accuracy = accuracy_score(y_test, predicted)

print(f'Out-of-bag score estimate: {rf.oob_score_:.3}') #예측이 얼마나 정확한가에 대한 추정을 수치로 나타낸 것
print(f'Mean accuracy score: {accuracy:.3}')
print("training Runtime: %0.2f Minutes"%((time.time() - start_vect)/60))

Out-of-bag score estimate: 1.0
Mean accuracy score: 0.998
training Runtime: 2.06 Minutes


In [59]:
rf.save('keras_NSLKDD_randomforest.h5')

AttributeError: 'RandomForestClassifier' object has no attribute 'save'